#!/usr/bin/env ansible-playbook
---

- name: run the playbook tasks on the localhost
  hosts: localhost
  become: no
  tasks:

  - name: Clone qutebrowser from Github
    git: 
      repo: https://github.com/qutebrowser/qutebrowser.git
      clone: yes
      recursive: no
      update: yes
      #dest: /opt/qutebrowser
      dest: ./qutebrowser

    
