#!/usr/bin/env ansible-playbook
---

- name: run the playbook tasks on the localhost
  hosts: localhost
  become: yes
  tasks:

  - name: Update repositories and install "{{ packages }}"  
    apt: 
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - git
      - vim
      - magic-wormhole
      - tmux
      - zsh
      - yadm
      - pass
      - i3
      - xorg
      - xinit
      - pulseaudio-utils

  - name: Install pip
    command: easy_install pip

#  - name: Install the following pip packages "{{ pips }}"
#    pip:
#      name: "{{ pips }}"
#    vars:
#      pips:
#      - tox

