#!/usr/bin/env ansible-playbook
---

- name: run the playbook tasks on the localhost
  hosts: localhost
  become: yes
  tasks:

  - name: Update repositories and install "{{ packages }}"  
    apt: 
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - git
      - vim
      - magic-wormhole
      - tmux
      - zsh
      - yadm
      - pass
      - i3
      - xorg
      - xinit
      # pulseaudio-utils are used to control audio vid pactl
      - pulseaudio-utils
      - curl
      - openvpn
      # fuse is used to be able to mount restic backups
      - fuse
      # dosfstools are used to format disks
      - dosfstools
      # aptitude is likely recommended to install packages by the user
      - aptitude

  - name: Install pip
    command: easy_install pip

#  - name: Install the following pip packages "{{ pips }}"
#    pip:
#      name: "{{ pips }}"
#    vars:
#      pips:
#      - tox

