---

- name: run the playbook tasks on the localhost
  hosts: localhost
  become: yes
  tasks:

  - name: Clone ansible from Github
    git: 
      repo: https://github.com/ansible/ansible.git
      clone: yes
      recursive: yes
      update: yes
      dest: /opt/ansible

  - name: Install pip
    command: easy_install pip
    
