---

- name: run the playbook tasks on the localhost
  hosts: localhost
  become: yes
  tasks:

  - name: Update repositories and install "{{ packages }}"  
    apt: 
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - libxcb-keysyms1-dev 
      - libpango1.0-dev   
      - libxcb-util0-dev   
      - xcb 
      - libxcb1-dev 
      - libxcb-icccm4-dev 
      - libyajl-dev 
      - libev-dev 
      - libxcb-xkb-dev 
      - libxcb-cursor-dev 
      - libxkbcommon-dev 
      - libxcb-xinerama0-dev 
      - libxkbcommon-x11-dev 
      - libstartup-notification0-dev 
      - libxcb-randr0-dev 
      - libxcb-xrm0 
      - libxcb-xrm-dev 
      - libxcb-shape0-dev 
      - xinit
      - i3status
                 
